// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxvfmfgjgsqujumtjggx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4dmZtZmdqZ3NxdWp1bXRqZ2d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDc5ODgsImV4cCI6MjA1OTIyMzk4OH0.UWTlhPWUxiNLlwPnusOBDCO59CopBOby0lDnCAtvfvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);